---
title: "Before we start"
---

To participate on the workshop you can either install R (>4.0) and Rstudio (see instructions bellow) or use an instance of R at RStudio Cloud.

#### Using RStudio Cloud

If you want to use RStudio Cloud you will need a free account. Go to [rstudio.cloud/](https://rstudio.cloud/) and follow de instructions to register. Keep in mind that the free account is limited to 15 hours per month and you don't want to use it all before the workshop.

We'll provide a link to a pre-configured RStudio project during the workshop. You don't have to do anything else. 

#### Installing R and RStudio

To install R and RStudio follow the instructions in [these videos](https://www.youtube.com/playlist?list=PLRPB0ZzEYegOZivdelOuEn-R-XUN-DOjd) by [Danielle Navarro](https://djnavarro.net/).

After you have everything installed, you'll need to install a few packages required for the workshop. Follow these instructions:

1. Open RStudio
2. On the console (the panel on the left) type the following commands

```{r, eval=FALSE}
install.packages("tidyverse")
install.packages("palmerpenguins")
```

4. Go to File -> New File -> R Markdown. Click on "Ok" to create a new file. RStudio will ask your permission to install several packages. Go ahead and do it. 

5. That's it. You can remove the file you just created.
